version: '3.7'
services:
  qubic:
    image: qubic-arm
    privileged: true
    restart: unless-stopped
    environment:
      - WALLET=${WALLET:?please make sure to set your REWARD_ADDRESS environment variable in the .env file}
      - T=${TH}
    
